---
STAGE: ${self:provider.stage}

DATABASE_PASS: ${ssm:/music_app/staging/DATABASE_PASS}
DATABASE_USER: ${ssm:/music_app/staging/DATABASE_USER}
DATABASE_NAME: ${ssm:/music_app/staging/DATABASE_NAME}

DATABASE_HOST:
  ? "Fn::GetAtt"
  :
    - AuroraInstance
    - Endpoint.Address


DATABASE_PORT:
  ? "Fn::GetAtt"
  :
    - AuroraInstance
    - Endpoint.Port

DATABASE_URI:
  Fn::Join:
  - ''
  - - "postgres://"
    - ${ssm:/music_app/staging/DATABASE_USER}
    - ":"
    - ${ssm:/music_app/staging/DATABASE_PASS}
    - "@"
    - ? "Fn::GetAtt"
      :
        - AuroraInstance
        - Endpoint.Address
    - ":"
    - ? "Fn::GetAtt"
      :
        - AuroraInstance
        - Endpoint.Port
    - "/"
    - ${ssm:/music_app/staging/DATABASE_NAME}

CLOUDFRONT_DOMAIN: !GetAtt AssetsDistribution.DomainName

SECRET_KEY: ${ssm:/music_app/staging/SECRET_KEY}
